// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// freq_c
IntegerVector freq_c(const IntegerVector& dat, const IntegerVector& lc_class);
RcppExport SEXP _grainchanger_freq_c(SEXP datSEXP, SEXP lc_classSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type lc_class(lc_classSEXP);
    rcpp_result_gen = Rcpp::wrap(freq_c(dat, lc_class));
    return rcpp_result_gen;
END_RCPP
}
// get_class_index_map
std::map<int, unsigned> get_class_index_map(const std::vector<int>& classes);
RcppExport SEXP _grainchanger_get_class_index_map(SEXP classesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<int>& >::type classes(classesSEXP);
    rcpp_result_gen = Rcpp::wrap(get_class_index_map(classes));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_xy_from_matrix
IntegerMatrix rcpp_xy_from_matrix(arma::imat x, Rcpp::Nullable<Rcpp::IntegerVector> cell);
RcppExport SEXP _grainchanger_rcpp_xy_from_matrix(SEXP xSEXP, SEXP cellSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::imat >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type cell(cellSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_xy_from_matrix(x, cell));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cell_from_xy
IntegerVector rcpp_cell_from_xy(arma::imat x, IntegerMatrix y);
RcppExport SEXP _grainchanger_rcpp_cell_from_xy(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::imat >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cell_from_xy(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_create_neighborhood
IntegerMatrix rcpp_create_neighborhood(arma::imat directions);
RcppExport SEXP _grainchanger_rcpp_create_neighborhood(SEXP directionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::imat >::type directions(directionsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_create_neighborhood(directions));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_focal_stats
NumericMatrix rcpp_focal_stats(const IntegerMatrix x, const arma::imat directions, const std::vector<int> classes);
RcppExport SEXP _grainchanger_rcpp_focal_stats(SEXP xSEXP, SEXP directionsSEXP, SEXP classesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::imat >::type directions(directionsSEXP);
    Rcpp::traits::input_parameter< const std::vector<int> >::type classes(classesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_focal_stats(x, directions, classes));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_unique_values
std::vector<int> rcpp_get_unique_values(const Rcpp::IntegerVector& x, bool na_omit);
RcppExport SEXP _grainchanger_rcpp_get_unique_values(SEXP xSEXP, SEXP na_omitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type na_omit(na_omitSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_unique_values(x, na_omit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_grainchanger_freq_c", (DL_FUNC) &_grainchanger_freq_c, 2},
    {"_grainchanger_get_class_index_map", (DL_FUNC) &_grainchanger_get_class_index_map, 1},
    {"_grainchanger_rcpp_xy_from_matrix", (DL_FUNC) &_grainchanger_rcpp_xy_from_matrix, 2},
    {"_grainchanger_rcpp_cell_from_xy", (DL_FUNC) &_grainchanger_rcpp_cell_from_xy, 2},
    {"_grainchanger_rcpp_create_neighborhood", (DL_FUNC) &_grainchanger_rcpp_create_neighborhood, 1},
    {"_grainchanger_rcpp_focal_stats", (DL_FUNC) &_grainchanger_rcpp_focal_stats, 3},
    {"_grainchanger_rcpp_get_unique_values", (DL_FUNC) &_grainchanger_rcpp_get_unique_values, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_grainchanger(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
