# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

freq_c <- function(dat, lc_class) {
    .Call('_grainchanger_freq_c', PACKAGE = 'grainchanger', dat, lc_class)
}

