# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

freq_c <- function(dat, lc_class) {
    .Call('_grainchanger_freq_c', PACKAGE = 'grainchanger', dat, lc_class)
}

get_class_index_map <- function(classes) {
    .Call('_grainchanger_get_class_index_map', PACKAGE = 'grainchanger', classes)
}

#' Coordinates from a matrix
#'
#' This function gets coordinates (row and column numbers) of the matrix cells.
#'
#' @param x A matrix
#' @param cell A vector of cell number.
#' If NULL, the coordinates will be calculated for the whole matrix
#' @keywords internal
rcpp_xy_from_matrix <- function(x, cell = NULL) {
    .Call('_grainchanger_rcpp_xy_from_matrix', PACKAGE = 'grainchanger', x, cell)
}

#' Get cell number
#'
#' Get cell number(s) of a matrix from row and column numbers.
#' Cell numbers start at 0 in the upper left corner,
#' and increase from top to bottom, and then from left to right.
#'
#' @param x A matrix
#' @param y A matrix with two columns (row and column numbers)
#' @keywords internal
rcpp_cell_from_xy <- function(x, y) {
    .Call('_grainchanger_rcpp_cell_from_xy', PACKAGE = 'grainchanger', x, y)
}

#' Create neighborhood coordinates
#'
#' This function creates a neighborhood coordinates matrix based on the directions parameter.
#'
#' @param directions The number of directions in which cells should be connected:
#' 4 (rook's case), 8 (queen's case), or a neighbourhood matrix.
#' The neighbourhood matrix should have one cell with value 0 (the focal cell),
#' and at least one cell with value 1 (the adjacent cells).
#' Cells with other values (e.g. NA) are ignored.
#' @keywords internal
rcpp_create_neighborhood <- function(directions) {
    .Call('_grainchanger_rcpp_create_neighborhood', PACKAGE = 'grainchanger', directions)
}

rcpp_focal_stats <- function(x, directions, classes) {
    .Call('_grainchanger_rcpp_focal_stats', PACKAGE = 'grainchanger', x, directions, classes)
}

rcpp_get_unique_values <- function(x, na_omit = TRUE) {
    .Call('_grainchanger_rcpp_get_unique_values', PACKAGE = 'grainchanger', x, na_omit)
}

