# Workflow derived from https://github.com/r-lib/actions/tree/v2-branch/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

on:
  push:
    branches: [main, development]
    paths: ["README.Rmd"]
  workflow_dispatch:

name: render-readme

jobs:
  render-readme:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rmarkdown, any::spatstat, any::terra, local::.

      - name: Render README files
        run: Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit README
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md man/figures/README-*
          git commit -m "Re-build README.md" || echo "No changes to commit"
          git push --force origin || echo "No changes to commit"
